### ISSUE TITLE
Failure to compile in 4.1.3

### ISSUE THREAD

**Issue by kwik-silver** [Mico27/GBS-DynamicMapPlugin-alpha#1]
I am using GB studio 4.1.3. This is a fairly basic project where I am using this metatiles plugin alongside your [GBS-scrollScenePlugin](https://github.com/Mico27/GBS-scrollScenePlugin). 

When I click run I get the following errors:

- src\core\collision.c:19: error 65: function 'bb_contains' already has body
- src\core\collision.c:36: error 65: function 'bb_intersects' already has body
- src\core\collision.c:51: error 65: function 'tile_at' already has body
 
I believe those errors mean the functions are already named somewhere. They do not seem to be called elsewhere in the codebase, so I went ahead and renamed those functions in collision.c and collision.h. I restarted GB Studio and tried to run again. I got numerous new errors:

src\core\meta_tiles.c:84: error 20: Undefined identifier 'tile_buffer'
src\core\meta_tiles.c:84: warning 154: converting integral to pointer without a cast
from type 'int fixed'
  to type 'void generic* fixed'
src\core\meta_tiles.c:87: error 20: Undefined identifier 'tile_buffer'
src\core\meta_tiles.c:87: error 22: Array or pointer required for '[]' operation 
src\core\meta_tiles.c:88: error 20: Undefined identifier 'tile_buffer'
src\core\meta_tiles.c:88: error 22: Array or pointer required for '[]' operation 
src\core\meta_tiles.c:88: error 47: indirections to different types assignment   
from type 'void'
  to type 'const-unsigned-char generic* auto'
src\core\meta_tiles.c:91: error 20: Undefined identifier 'tile_buffer'
src\core\meta_tiles.c:91: warning 154: converting integral to pointer without a cast
from type 'int fixed'
  to type 'const-unsigned-char generic* fixed'

Any way to move forward? I am really hoping to use these two plugins together in the latest version of GB Studio!

**Comment by kwik-silver** [comment]
Also: this is in mono mode. No palettes on the metatile background.

**Comment by Mico27** [comment]
The metatiles plugin is currently not compatible with the scrollscene plugin
